sudo: required
services:
  - docker

before_install:
  - docker build -t steelman72/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true steelman72/docker-react npm run test -- --coverage

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-637220785361"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
